// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc2;

public final class Federal {
  private Federal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filetransfer_request_init_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filetransfer_request_init_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filetransfer_request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filetransfer_request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filetransfer_response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filetransfer_response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filetransfer_request_detect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filetransfer_request_detect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filetransfer_response_detect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filetransfer_response_detect_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rfederal.proto\022\014filetransfer\"I\n\014request" +
      "_init\022\023\n\013ctx_content\030\001 \001(\014\022\025\n\rparas_cont" +
      "ent\030\002 \001(\014\022\r\n\005round\030\003 \001(\005\"/\n\007request\022\025\n\rp" +
      "aras_content\030\001 \001(\014\022\r\n\005round\030\002 \001(\005\"T\n\010res" +
      "ponse\022\025\n\rparas_content\030\001 \001(\014\022\026\n\016result_c" +
      "ontent\030\002 \001(\014\022\031\n\021gradients_content\030\003 \001(\014\"" +
      "\020\n\016request_detect\"(\n\017response_detect\022\025\n\r" +
      "result_detect\030\001 \001(\0142\321\001\n\013FileService\022A\n\013p" +
      "rocessinit\022\032.filetransfer.request_init\032\026" +
      ".filetransfer.response\0228\n\007process\022\025.file" +
      "transfer.request\032\026.filetransfer.response" +
      "\022E\n\006detect\022\034.filetransfer.request_detect" +
      "\032\035.filetransfer.response_detectB\002P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_filetransfer_request_init_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_filetransfer_request_init_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filetransfer_request_init_descriptor,
        new String[] { "CtxContent", "ParasContent", "Round", });
    internal_static_filetransfer_request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_filetransfer_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filetransfer_request_descriptor,
        new String[] { "ParasContent", "Round", });
    internal_static_filetransfer_response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_filetransfer_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filetransfer_response_descriptor,
        new String[] { "ParasContent", "ResultContent", "GradientsContent", });
    internal_static_filetransfer_request_detect_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_filetransfer_request_detect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filetransfer_request_detect_descriptor,
        new String[] { });
    internal_static_filetransfer_response_detect_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_filetransfer_response_detect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filetransfer_response_detect_descriptor,
        new String[] { "ResultDetect", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
