// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc2;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filetransfer.request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *参数文件内容
   * </pre>
   *
   * <code>bytes paras_content = 1;</code>
   */
  com.google.protobuf.ByteString getParasContent();

  /**
   * <pre>
   *当前轮次
   * </pre>
   *
   * <code>int32 round = 2;</code>
   */
  int getRound();
}
