// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc2;

/**
 * Protobuf type {@code filetransfer.response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:filetransfer.response)
        ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    parasContent_ = com.google.protobuf.ByteString.EMPTY;
    resultContent_ = com.google.protobuf.ByteString.EMPTY;
    gradientsContent_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            parasContent_ = input.readBytes();
            break;
          }
          case 18: {

            resultContent_ = input.readBytes();
            break;
          }
          case 26: {

            gradientsContent_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Federal.internal_static_filetransfer_response_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Federal.internal_static_filetransfer_response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Response.class, Builder.class);
  }

  public static final int PARAS_CONTENT_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString parasContent_;
  /**
   * <pre>
   *参数文件内容
   * </pre>
   *
   * <code>bytes paras_content = 1;</code>
   */
  public com.google.protobuf.ByteString getParasContent() {
    return parasContent_;
  }

  public static final int RESULT_CONTENT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString resultContent_;
  /**
   * <pre>
   *结果文件内容，csv格式
   * </pre>
   *
   * <code>bytes result_content = 2;</code>
   */
  public com.google.protobuf.ByteString getResultContent() {
    return resultContent_;
  }

  public static final int GRADIENTS_CONTENT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString gradientsContent_;
  /**
   * <pre>
   *梯度文件，npy格式
   * </pre>
   *
   * <code>bytes gradients_content = 3;</code>
   */
  public com.google.protobuf.ByteString getGradientsContent() {
    return gradientsContent_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!parasContent_.isEmpty()) {
      output.writeBytes(1, parasContent_);
    }
    if (!resultContent_.isEmpty()) {
      output.writeBytes(2, resultContent_);
    }
    if (!gradientsContent_.isEmpty()) {
      output.writeBytes(3, gradientsContent_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!parasContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, parasContent_);
    }
    if (!resultContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, resultContent_);
    }
    if (!gradientsContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, gradientsContent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Response)) {
      return super.equals(obj);
    }
    Response other = (Response) obj;

    boolean result = true;
    result = result && getParasContent()
        .equals(other.getParasContent());
    result = result && getResultContent()
        .equals(other.getResultContent());
    result = result && getGradientsContent()
        .equals(other.getGradientsContent());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARAS_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getParasContent().hashCode();
    hash = (37 * hash) + RESULT_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getResultContent().hashCode();
    hash = (37 * hash) + GRADIENTS_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getGradientsContent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code filetransfer.response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:filetransfer.response)
          ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Federal.internal_static_filetransfer_response_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Federal.internal_static_filetransfer_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    // Construct using filetransfer.response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      parasContent_ = com.google.protobuf.ByteString.EMPTY;

      resultContent_ = com.google.protobuf.ByteString.EMPTY;

      gradientsContent_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Federal.internal_static_filetransfer_response_descriptor;
    }

    public Response getDefaultInstanceForType() {
      return Response.getDefaultInstance();
    }

    public Response build() {
      Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Response buildPartial() {
      Response result = new Response(this);
      result.parasContent_ = parasContent_;
      result.resultContent_ = resultContent_;
      result.gradientsContent_ = gradientsContent_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Response) {
        return mergeFrom((Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Response other) {
      if (other == Response.getDefaultInstance()) return this;
      if (other.getParasContent() != com.google.protobuf.ByteString.EMPTY) {
        setParasContent(other.getParasContent());
      }
      if (other.getResultContent() != com.google.protobuf.ByteString.EMPTY) {
        setResultContent(other.getResultContent());
      }
      if (other.getGradientsContent() != com.google.protobuf.ByteString.EMPTY) {
        setGradientsContent(other.getGradientsContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString parasContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *参数文件内容
     * </pre>
     *
     * <code>bytes paras_content = 1;</code>
     */
    public com.google.protobuf.ByteString getParasContent() {
      return parasContent_;
    }
    /**
     * <pre>
     *参数文件内容
     * </pre>
     *
     * <code>bytes paras_content = 1;</code>
     */
    public Builder setParasContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parasContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数文件内容
     * </pre>
     *
     * <code>bytes paras_content = 1;</code>
     */
    public Builder clearParasContent() {
      
      parasContent_ = getDefaultInstance().getParasContent();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString resultContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *结果文件内容，csv格式
     * </pre>
     *
     * <code>bytes result_content = 2;</code>
     */
    public com.google.protobuf.ByteString getResultContent() {
      return resultContent_;
    }
    /**
     * <pre>
     *结果文件内容，csv格式
     * </pre>
     *
     * <code>bytes result_content = 2;</code>
     */
    public Builder setResultContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *结果文件内容，csv格式
     * </pre>
     *
     * <code>bytes result_content = 2;</code>
     */
    public Builder clearResultContent() {
      
      resultContent_ = getDefaultInstance().getResultContent();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString gradientsContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *梯度文件，npy格式
     * </pre>
     *
     * <code>bytes gradients_content = 3;</code>
     */
    public com.google.protobuf.ByteString getGradientsContent() {
      return gradientsContent_;
    }
    /**
     * <pre>
     *梯度文件，npy格式
     * </pre>
     *
     * <code>bytes gradients_content = 3;</code>
     */
    public Builder setGradientsContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gradientsContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *梯度文件，npy格式
     * </pre>
     *
     * <code>bytes gradients_content = 3;</code>
     */
    public Builder clearGradientsContent() {
      
      gradientsContent_ = getDefaultInstance().getGradientsContent();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:filetransfer.response)
  }

  // @@protoc_insertion_point(class_scope:filetransfer.response)
  private static final Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Response();
  }

  public static Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  public Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

