// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_server.grpc;

public final class Federal {
  private Federal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Request_init_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Request_init_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Response_init_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Response_init_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rfederal.proto\022\007example\"\016\n\014Request_init" +
      "\"D\n\rResponse_init\022\031\n\021para_file_content\030\001" +
      " \001(\014\022\030\n\020ctx_file_content\030\002 \001(\014\"[\n\007Reques" +
      "t\022\016\n\006number\030\001 \001(\005\022\r\n\005round\030\002 \001(\005\022\036\n\026encr" +
      "ypted_file_content\030\003 \003(\014\022\021\n\tgradients\030\004 " +
      "\003(\014\"9\n\010Response\022\035\n\025agg_para_file_content" +
      "\030\001 \001(\014\022\016\n\006result\030\002 \001(\0142\215\001\n\020ArithmeticSer" +
      "ver\022<\n\013server_init\022\025.example.Request_ini" +
      "t\032\026.example.Response_init\022;\n\024send_aggreg" +
      "ated_para\022\020.example.Request\032\021.example.Re" +
      "sponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_example_Request_init_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Request_init_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Request_init_descriptor,
        new String[] { });
    internal_static_example_Response_init_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_Response_init_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Response_init_descriptor,
        new String[] { "ParaFileContent", "CtxFileContent", });
    internal_static_example_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_example_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Request_descriptor,
        new String[] { "Number", "Round", "EncryptedFileContent", "Gradients", });
    internal_static_example_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_example_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Response_descriptor,
        new String[] { "AggParaFileContent", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
