// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_server.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *客户端数量
   * </pre>
   *
   * <code>int32 number = 1;</code>
   */
  int getNumber();

  /**
   * <pre>
   *当前轮次
   * </pre>
   *
   * <code>int32 round = 2;</code>
   */
  int getRound();

  /**
   * <pre>
   *加密文件内容
   * </pre>
   *
   * <code>repeated bytes encrypted_file_content = 3;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getEncryptedFileContentList();
  /**
   * <pre>
   *加密文件内容
   * </pre>
   *
   * <code>repeated bytes encrypted_file_content = 3;</code>
   */
  int getEncryptedFileContentCount();
  /**
   * <pre>
   *加密文件内容
   * </pre>
   *
   * <code>repeated bytes encrypted_file_content = 3;</code>
   */
  com.google.protobuf.ByteString getEncryptedFileContent(int index);

  /**
   * <pre>
   *模型梯度文件
   * </pre>
   *
   * <code>repeated bytes gradients = 4;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getGradientsList();
  /**
   * <pre>
   *模型梯度文件
   * </pre>
   *
   * <code>repeated bytes gradients = 4;</code>
   */
  int getGradientsCount();
  /**
   * <pre>
   *模型梯度文件
   * </pre>
   *
   * <code>repeated bytes gradients = 4;</code>
   */
  com.google.protobuf.ByteString getGradients(int index);
}
