// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_server.grpc;

public interface RequestInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Request_init)
    com.google.protobuf.MessageOrBuilder {
}
