// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_server.grpc;

public interface ResponseInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Response_init)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *参数文件内容
   * </pre>
   *
   * <code>bytes para_file_content = 1;</code>
   */
  com.google.protobuf.ByteString getParaFileContent();

  /**
   * <pre>
   *ctx密钥文件内容
   * </pre>
   *
   * <code>bytes ctx_file_content = 2;</code>
   */
  com.google.protobuf.ByteString getCtxFileContent();
}
