// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_server.grpc;

/**
 * Protobuf type {@code example.Response_init}
 */
public  final class ResponseInit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:example.Response_init)
        ResponseInitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response_init.newBuilder() to construct.
  private ResponseInit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseInit() {
    paraFileContent_ = com.google.protobuf.ByteString.EMPTY;
    ctxFileContent_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseInit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            paraFileContent_ = input.readBytes();
            break;
          }
          case 18: {

            ctxFileContent_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Federal.internal_static_example_Response_init_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Federal.internal_static_example_Response_init_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResponseInit.class, ResponseInit.Builder.class);
  }

  public static final int PARA_FILE_CONTENT_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString paraFileContent_;
  /**
   * <pre>
   *参数文件内容
   * </pre>
   *
   * <code>bytes para_file_content = 1;</code>
   */
  public com.google.protobuf.ByteString getParaFileContent() {
    return paraFileContent_;
  }

  public static final int CTX_FILE_CONTENT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString ctxFileContent_;
  /**
   * <pre>
   *ctx密钥文件内容
   * </pre>
   *
   * <code>bytes ctx_file_content = 2;</code>
   */
  public com.google.protobuf.ByteString getCtxFileContent() {
    return ctxFileContent_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!paraFileContent_.isEmpty()) {
      output.writeBytes(1, paraFileContent_);
    }
    if (!ctxFileContent_.isEmpty()) {
      output.writeBytes(2, ctxFileContent_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!paraFileContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, paraFileContent_);
    }
    if (!ctxFileContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, ctxFileContent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResponseInit)) {
      return super.equals(obj);
    }
    ResponseInit other = (ResponseInit) obj;

    boolean result = true;
    result = result && getParaFileContent()
        .equals(other.getParaFileContent());
    result = result && getCtxFileContent()
        .equals(other.getCtxFileContent());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARA_FILE_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getParaFileContent().hashCode();
    hash = (37 * hash) + CTX_FILE_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getCtxFileContent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResponseInit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseInit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseInit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseInit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseInit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseInit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseInit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResponseInit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResponseInit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ResponseInit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResponseInit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResponseInit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResponseInit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.Response_init}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.Response_init)
          ResponseInitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Federal.internal_static_example_Response_init_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Federal.internal_static_example_Response_init_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseInit.class, ResponseInit.Builder.class);
    }

    // Construct using example.Response_init.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      paraFileContent_ = com.google.protobuf.ByteString.EMPTY;

      ctxFileContent_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Federal.internal_static_example_Response_init_descriptor;
    }

    public ResponseInit getDefaultInstanceForType() {
      return ResponseInit.getDefaultInstance();
    }

    public ResponseInit build() {
      ResponseInit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ResponseInit buildPartial() {
      ResponseInit result = new ResponseInit(this);
      result.paraFileContent_ = paraFileContent_;
      result.ctxFileContent_ = ctxFileContent_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResponseInit) {
        return mergeFrom((ResponseInit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResponseInit other) {
      if (other == ResponseInit.getDefaultInstance()) return this;
      if (other.getParaFileContent() != com.google.protobuf.ByteString.EMPTY) {
        setParaFileContent(other.getParaFileContent());
      }
      if (other.getCtxFileContent() != com.google.protobuf.ByteString.EMPTY) {
        setCtxFileContent(other.getCtxFileContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ResponseInit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ResponseInit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString paraFileContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *参数文件内容
     * </pre>
     *
     * <code>bytes para_file_content = 1;</code>
     */
    public com.google.protobuf.ByteString getParaFileContent() {
      return paraFileContent_;
    }
    /**
     * <pre>
     *参数文件内容
     * </pre>
     *
     * <code>bytes para_file_content = 1;</code>
     */
    public Builder setParaFileContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paraFileContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数文件内容
     * </pre>
     *
     * <code>bytes para_file_content = 1;</code>
     */
    public Builder clearParaFileContent() {
      
      paraFileContent_ = getDefaultInstance().getParaFileContent();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ctxFileContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *ctx密钥文件内容
     * </pre>
     *
     * <code>bytes ctx_file_content = 2;</code>
     */
    public com.google.protobuf.ByteString getCtxFileContent() {
      return ctxFileContent_;
    }
    /**
     * <pre>
     *ctx密钥文件内容
     * </pre>
     *
     * <code>bytes ctx_file_content = 2;</code>
     */
    public Builder setCtxFileContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ctxFileContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ctx密钥文件内容
     * </pre>
     *
     * <code>bytes ctx_file_content = 2;</code>
     */
    public Builder clearCtxFileContent() {
      
      ctxFileContent_ = getDefaultInstance().getCtxFileContent();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:example.Response_init)
  }

  // @@protoc_insertion_point(class_scope:example.Response_init)
  private static final ResponseInit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResponseInit();
  }

  public static ResponseInit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseInit>
      PARSER = new com.google.protobuf.AbstractParser<ResponseInit>() {
    public ResponseInit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseInit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseInit> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResponseInit> getParserForType() {
    return PARSER;
  }

  public ResponseInit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

