// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_server.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *聚合后的参数文件内容
   * </pre>
   *
   * <code>bytes agg_para_file_content = 1;</code>
   */
  com.google.protobuf.ByteString getAggParaFileContent();

  /**
   * <pre>
   *聚合后模型的结果文件，csv文件
   * </pre>
   *
   * <code>bytes result = 2;</code>
   */
  com.google.protobuf.ByteString getResult();
}
