// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc;

public interface RequestDetectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filetransfer.request_detect)
    com.google.protobuf.MessageOrBuilder {
}
