// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc;

public interface RequestInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filetransfer.request_init)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *密钥文件内容
   * </pre>
   *
   * <code>bytes ctx_content = 1;</code>
   */
  com.google.protobuf.ByteString getCtxContent();

  /**
   * <pre>
   *参数文件内容
   * </pre>
   *
   * <code>bytes paras_content = 2;</code>
   */
  com.google.protobuf.ByteString getParasContent();

  /**
   * <pre>
   *当前轮次从1开始
   * </pre>
   *
   * <code>int32 round = 3;</code>
   */
  int getRound();
}
