// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc;

public interface ResponseDetectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filetransfer.response_detect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *有问题的流
   * </pre>
   *
   * <code>bytes result_detect = 1;</code>
   */
  com.google.protobuf.ByteString getResultDetect();
}
