// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.AI_Security.AI_Security_client.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filetransfer.response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *参数文件内容
   * </pre>
   *
   * <code>bytes paras_content = 1;</code>
   */
  com.google.protobuf.ByteString getParasContent();

  /**
   * <pre>
   *结果文件内容，csv格式
   * </pre>
   *
   * <code>bytes result_content = 2;</code>
   */
  com.google.protobuf.ByteString getResultContent();

  /**
   * <pre>
   *梯度文件，npy格式
   * </pre>
   *
   * <code>bytes gradients_content = 3;</code>
   */
  com.google.protobuf.ByteString getGradientsContent();
}
