// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal1.proto

package com.AI_Security.AI_Security_client.grpc1;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string url = 2;</code>
   */
  String getUrl();
  /**
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string type = 3;</code>
   */
  String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string datainfoReq = 4;</code>
   */
  String getDatainfoReq();
  /**
   * <code>string datainfoReq = 4;</code>
   */
  com.google.protobuf.ByteString
      getDatainfoReqBytes();
}
