// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal1.proto

package com.AI_Security.AI_Security_client.grpc1;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string datainfoRet = 2;</code>
   */
  String getDatainfoRet();
  /**
   * <code>string datainfoRet = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatainfoRetBytes();

  /**
   * <code>string time = 3;</code>
   */
  String getTime();
  /**
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>int32 n = 4;</code>
   */
  int getN();

  /**
   * <code>int32 n2 = 5;</code>
   */
  int getN2();

  /**
   * <code>int32 n3 = 6;</code>
   */
  int getN3();

  /**
   * <code>repeated string x1 = 7;</code>
   */
  java.util.List<String>
      getX1List();
  /**
   * <code>repeated string x1 = 7;</code>
   */
  int getX1Count();
  /**
   * <code>repeated string x1 = 7;</code>
   */
  String getX1(int index);
  /**
   * <code>repeated string x1 = 7;</code>
   */
  com.google.protobuf.ByteString
      getX1Bytes(int index);

  /**
   * <code>repeated int32 y1 = 8;</code>
   */
  java.util.List<Integer> getY1List();
  /**
   * <code>repeated int32 y1 = 8;</code>
   */
  int getY1Count();
  /**
   * <code>repeated int32 y1 = 8;</code>
   */
  int getY1(int index);

  /**
   * <code>int32 r1 = 9;</code>
   */
  int getR1();

  /**
   * <code>int32 r2 = 10;</code>
   */
  int getR2();

  /**
   * <code>int32 r3 = 11;</code>
   */
  int getR3();

  /**
   * <code>int32 r21 = 12;</code>
   */
  int getR21();

  /**
   * <code>int32 r22 = 13;</code>
   */
  int getR22();

  /**
   * <code>int32 c1 = 14;</code>
   */
  int getC1();

  /**
   * <code>int32 c2 = 15;</code>
   */
  int getC2();

  /**
   * <code>repeated string columns = 16;</code>
   */
  java.util.List<String>
      getColumnsList();
  /**
   * <code>repeated string columns = 16;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated string columns = 16;</code>
   */
  String getColumns(int index);
  /**
   * <code>repeated string columns = 16;</code>
   */
  com.google.protobuf.ByteString
      getColumnsBytes(int index);

  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  java.util.List<Response.Arr>
      getArrList();
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  Response.Arr getArr(int index);
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  int getArrCount();
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  java.util.List<? extends Response.ArrOrBuilder>
      getArrOrBuilderList();
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  Response.ArrOrBuilder getArrOrBuilder(
      int index);
}
